services:
  db:
    image: postgres:15
    container_name: conjoin-postgres
    environment:
      POSTGRES_DB: conjoin_ai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d conjoin_ai"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: pgAdmin for database management (uncomment if needed)
  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   container_name: conjoin-pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@conjoin.ai
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - db

volumes:
  postgres_data:
    driver: local
