import pandas as pd
import numpy as np


mh_sug_json = [
    {"cat": "work anxiety", "activity": "contact community", "severity": "4+", "alone": "alone", "duration": "10,20", "location": "work or home"},
    {"cat": "work anxiety", "activity": "phone friend", "severity": "4+", "alone": "alone", "duration": "5,10,20", "location": "work or home"},
    {
        "cat": "work anxiety",
        "activity": "grounding",
        "severity": "4+",
        "alone": "alone or combination",
        "duration": "2,5,10",
        "location": "work or home",
    },
    {"cat": "work anxiety", "activity": "podcast - news", "severity": 4, "alone": "alone", "duration": 15, "location": "work or home"},
    {"cat": "work anxiety", "activity": "podcast - history", "severity": 4, "alone": "alone", "duration": 60, "location": "home"},
    {"cat": "work anxiety", "activity": "you tube - animal shorts", "severity": 4, "alone": "alone", "duration": 15, "location": "work or home"},
    {"cat": "work anxiety", "activity": "you tube - film reviews", "severity": 4, "alone": "alone", "duration": 15, "location": "work or home"},
    {"cat": "work anxiety", "activity": "go for a walk", "severity": None, "alone": "alone or combination", "duration": 30, "location": None},
    {"cat": "work anxiety", "activity": "go for a light run", "severity": 4, "alone": "alone or combination", "duration": 30, "location": "home"},
    {
        "cat": "work anxiety",
        "activity": "affirmation 1 - work",
        "severity": 3,
        "alone": "alone or combination",
        "duration": 1,
        "location": "work or home",
    },
    {"cat": "work anxiety", "activity": "podcast - news", "severity": 3, "alone": "alone", "duration": 15, "location": "work or home"},
    {"cat": "work anxiety", "activity": "podcast - history", "severity": 3, "alone": "alone or combination", "duration": 60, "location": "home"},
    {
        "cat": "work anxiety",
        "activity": "you tube - animal shorts",
        "severity": 3,
        "alone": "alone or combination",
        "duration": 15,
        "location": "work or home",
    },
    {
        "cat": "work anxiety",
        "activity": "you tube - film reviews",
        "severity": 3,
        "alone": "alone or combination",
        "duration": 15,
        "location": "work or home",
    },
    {"cat": "work anxiety", "activity": "go for a walk", "severity": 3, "alone": "alone or combination", "duration": 30, "location": "home"},
    {"cat": "work anxiety", "activity": "go for a light run", "severity": 3, "alone": "alone or combination", "duration": 30, "location": "home"},
    {"cat": "work anxiety", "activity": "breathing 4-7-8", "severity": 3, "alone": "alone ", "duration": 5, "location": "work or home"},
    {
        "cat": "work anxiety",
        "activity": "Check diary for upbeat moments",
        "severity": 2,
        "alone": "alone or combination",
        "duration": 15,
        "location": "work or home",
    },
    {
        "cat": "work anxiety",
        "activity": "Prepare a review of your meeting",
        "severity": 3,
        "alone": "alone ",
        "duration": 30,
        "location": "after meeting",
    },
    {
        "cat": "work anxiety",
        "activity": "Prepare key points prior to meeting",
        "severity": None,
        "alone": "alone ",
        "duration": 30,
        "location": "before meeting",
    },
    {
        "cat": "work anxiety",
        "activity": "affirmation 1 - work",
        "severity": 2,
        "alone": "alone or combination",
        "duration": 1,
        "location": "work or home",
    },
    {
        "cat": "work anxiety",
        "activity": "play list - calm",
        "severity": 2,
        "alone": "alone or combination",
        "duration": 30,
        "location": "work or home",
    },
    {"cat": "work anxiety", "activity": "quick yoga", "severity": 2, "alone": "alone ", "duration": 30, "location": "home"},
    {"cat": "work anxiety", "activity": "breathing 4-7-8", "severity": 2, "alone": "alone ", "duration": 5, "location": "work or home"},
    {"cat": "work anxiety", "activity": "go for a walk", "severity": 2, "alone": "alone or combination", "duration": 30, "location": "home"},
    {"cat": "work anxiety", "activity": "Visualise sea", "severity": 2, "alone": "alone ", "duration": 5, "location": "home"},
    {"cat": "work anxiety", "activity": "Check diary for calm moments", "severity": 2, "alone": "alone ", "duration": 5, "location": "work or home"},
    {
        "cat": "work anxiety",
        "activity": "Check diary for scenic moments",
        "severity": 2,
        "alone": "alone ",
        "duration": 5,
        "location": "work or home",
    },
    {
        "cat": "work anxiety",
        "activity": "Prepare a review of your meeting",
        "severity": 2,
        "alone": "alone or combination",
        "duration": 30,
        "location": "after meeting",
    },
    {
        "cat": "work anxiety",
        "activity": "Prepare key points prior to meeting",
        "severity": 2,
        "alone": "alone ",
        "duration": 30,
        "location": "before meeting",
    },
    {"cat": "social anxiety", "activity": "contact community", "severity": "4+", "alone": "alone", "duration": "10,20", "location": None},
    {"cat": "social anxiety", "activity": "phone friend", "severity": "4+", "alone": "alone", "duration": "5,10,20", "location": None},
    {"cat": "social anxiety", "activity": "grounding", "severity": "4+", "alone": "alone or combination", "duration": "2,5,10", "location": None},
    {"cat": "social anxiety", "activity": "affirmation 2 - social", "severity": 4, "alone": "alone", "duration": 1, "location": None},
    {"cat": "social anxiety", "activity": "humming breathing", "severity": 4, "alone": "alone or combination", "duration": 10, "location": None},
    {"cat": "social anxiety", "activity": "playlist - techno", "severity": 4, "alone": "alone", "duration": 15, "location": None},
    {"cat": "social anxiety", "activity": "podcast - news", "severity": 4, "alone": "alone or combination", "duration": 15, "location": None},
    {"cat": "social anxiety", "activity": "you tube - news updates", "severity": 4, "alone": "alone", "duration": 15, "location": None},
    {"cat": "social anxiety", "activity": "go for a light run", "severity": 4, "alone": "alone", "duration": 30, "location": None},
    {"cat": "social anxiety", "activity": "intense yoga", "severity": 4, "alone": "alone", "duration": 60, "location": None},
    {"cat": "social anxiety", "activity": "go shopping (supermarket)", "severity": 4, "alone": "alone", "duration": 30, "location": None},
    {"cat": "social anxiety", "activity": "go to Starbucks for a herbal tea", "severity": 4, "alone": "alone", "duration": 20, "location": None},
    {"cat": "social anxiety", "activity": "affirmation 2 - social", "severity": 3, "alone": "alone", "duration": 1, "location": None},
    {"cat": "social anxiety", "activity": "humming breathing", "severity": 3, "alone": "alone", "duration": 10, "location": None},
    {"cat": "social anxiety", "activity": "playlist - techno", "severity": 3, "alone": "alone", "duration": 15, "location": None},
    {"cat": "social anxiety", "activity": "podcast - news", "severity": 3, "alone": "alone", "duration": 15, "location": None},
    {"cat": "social anxiety", "activity": "you tube - news updates", "severity": 3, "alone": "alone", "duration": 15, "location": None},
    {"cat": "social anxiety", "activity": "go for a light run", "severity": 3, "alone": "alone", "duration": 30, "location": None},
    {"cat": "social anxiety", "activity": "intense yoga", "severity": 3, "alone": "alone", "duration": 60, "location": None},
    {"cat": "social anxiety", "activity": "go shopping (supermarket)", "severity": 3, "alone": "alone", "duration": 30, "location": None},
    {"cat": "social anxiety", "activity": "go to Starbucks for a herbal tea", "severity": 3, "alone": "alone", "duration": 20, "location": None},
    {"cat": "social anxiety", "activity": "Check diary for fun social moments", "severity": None, "alone": "alone", "duration": 15, "location": None},
    {"cat": "social anxiety", "activity": "Visit interaction check in", "severity": 3, "alone": "alone", "duration": 20, "location": None},
    {"cat": "social anxiety", "activity": "walk with friend", "severity": 3, "alone": "alone", "duration": "30,60", "location": None},
    {"cat": "social anxiety", "activity": "walk and phone friend", "severity": 3, "alone": "alone", "duration": "15,30", "location": None},
    {"cat": "social anxiety", "activity": "affirmation 2 - social", "severity": 2, "alone": "alone", "duration": 1, "location": None},
    {"cat": "social anxiety", "activity": "play list - calm", "severity": 2, "alone": "alone", "duration": 30, "location": None},
    {"cat": "social anxiety", "activity": "humming breathing", "severity": 2, "alone": "alone", "duration": 10, "location": None},
    {"cat": "social anxiety", "activity": "playlist - techno", "severity": 2, "alone": "alone", "duration": 15, "location": None},
    {"cat": "social anxiety", "activity": "podcast - news", "severity": 2, "alone": "alone", "duration": 15, "location": None},
    {"cat": "social anxiety", "activity": "you tube - news updates", "severity": 2, "alone": "alone", "duration": 15, "location": None},
    {"cat": "social anxiety", "activity": "go for a light run", "severity": 2, "alone": "alone", "duration": 30, "location": None},
    {"cat": "social anxiety", "activity": "quick yoga", "severity": 2, "alone": "alone", "duration": 20, "location": None},
    {"cat": "social anxiety", "activity": "go for a walk", "severity": 2, "alone": "alone", "duration": 30, "location": None},
    {"cat": "social anxiety", "activity": "Visualise birds", "severity": 2, "alone": "alone", "duration": 5, "location": None},
    {"cat": "social anxiety", "activity": "Visualise woodland", "severity": 2, "alone": "alone", "duration": 5, "location": None},
    {"cat": "social anxiety", "activity": "Check diary for group activity moments", "severity": 2, "alone": "alone", "duration": 5, "location": None},
    {"cat": "social anxiety", "activity": "Check diary for fun eating out moments", "severity": 2, "alone": "alone", "duration": 5, "location": None},
    {"cat": "social anxiety", "activity": "Visit interaction check in", "severity": 2, "alone": "alone", "duration": 20, "location": None},
    {"cat": "social anxiety", "activity": "walk with friend", "severity": 2, "alone": "alone", "duration": "30,60", "location": None},
    {"cat": "social anxiety", "activity": "walk and phone friend", "severity": 2, "alone": "alone", "duration": "15,30", "location": None},
    {"cat": "family anxiety", "activity": "contact community", "severity": "4+", "alone": "alone", "duration": "10,20", "location": None},
    {"cat": "family anxiety", "activity": "phone friend", "severity": "4+", "alone": "alone", "duration": "5,10,20", "location": None},
    {"cat": "family anxiety", "activity": "grounding", "severity": "4+", "alone": "alone or combination", "duration": "2,5,10", "location": None},
    {"cat": "family anxiety", "activity": "affirmation 3 - family", "severity": 4, "alone": "alone", "duration": 1, "location": None},
    {"cat": "family anxiety", "activity": "resonance breathing", "severity": 4, "alone": "alone or combination", "duration": 10, "location": None},
    {"cat": "family anxiety", "activity": "playlist - mixed", "severity": 4, "alone": "alone", "duration": 15, "location": None},
    {"cat": "family anxiety", "activity": "podcast - news", "severity": 4, "alone": "alone or combination", "duration": 15, "location": None},
    {"cat": "family anxiety", "activity": "on line chess", "severity": 4, "alone": "alone", "duration": 15, "location": None},
    {"cat": "family anxiety", "activity": "go for a light run", "severity": 4, "alone": "alone", "duration": 30, "location": None},
    {"cat": "family anxiety", "activity": "intense yoga", "severity": 4, "alone": "alone", "duration": 60, "location": None},
    {"cat": "family anxiety", "activity": "go to Starbucks for a herbal tea", "severity": 4, "alone": "alone", "duration": 20, "location": None},
    {"cat": "family anxiety", "activity": "affirmation 3 - family", "severity": 3, "alone": "alone", "duration": 1, "location": None},
    {"cat": "family anxiety", "activity": "resonance breathing", "severity": 3, "alone": "alone", "duration": 10, "location": None},
    {"cat": "family anxiety", "activity": "playlist - mixed", "severity": 3, "alone": "alone", "duration": 15, "location": None},
    {"cat": "family anxiety", "activity": "podcast - news", "severity": 3, "alone": "alone", "duration": 15, "location": None},
    {"cat": "family anxiety", "activity": "on line chess", "severity": 3, "alone": "alone", "duration": 15, "location": None},
    {"cat": "family anxiety", "activity": "go for a light run", "severity": 3, "alone": "alone", "duration": 30, "location": None},
    {"cat": "family anxiety", "activity": "intense yoga", "severity": 3, "alone": "alone", "duration": 60, "location": None},
    {"cat": "family anxiety", "activity": "go to Starbucks for a herbal tea", "severity": 3, "alone": "alone", "duration": 20, "location": None},
    {"cat": "family anxiety", "activity": "Check diary for fun family moments", "severity": None, "alone": "alone", "duration": 15, "location": None},
    {"cat": "family anxiety", "activity": "Visit interaction check in", "severity": 2, "alone": "alone", "duration": 20, "location": None},
    {"cat": "family anxiety", "activity": "walk with friend", "severity": 2, "alone": "alone", "duration": "30,60", "location": None},
    {"cat": "family anxiety", "activity": "walk and phone friend", "severity": 2, "alone": "alone", "duration": "15,30", "location": None},
    {
        "cat": "family anxiety",
        "activity": "follow on call with father",
        "severity": 2,
        "alone": "alone or combination",
        "duration": 15,
        "location": "after call with father",
    },
    {
        "cat": "family anxiety",
        "activity": "contact community (sister)",
        "severity": 2,
        "alone": "alone or combination",
        "duration": 15,
        "location": "after call with father",
    },
    {"cat": "family anxiety", "activity": "affirmation 3 - family", "severity": 2, "alone": "alone", "duration": 1, "location": None},
    {"cat": "family anxiety", "activity": "play list - mixed", "severity": 2, "alone": "alone", "duration": 30, "location": None},
    {"cat": "family anxiety", "activity": "resonance breathing", "severity": 2, "alone": "alone", "duration": 10, "location": None},
    {"cat": "family anxiety", "activity": "on line chess", "severity": 2, "alone": "alone", "duration": 15, "location": None},
    {"cat": "family anxiety", "activity": "podcast - news", "severity": 2, "alone": "alone", "duration": 15, "location": None},
    {"cat": "family anxiety", "activity": "you tube - news updates", "severity": 2, "alone": "alone", "duration": 15, "location": None},
    {"cat": "family anxiety", "activity": "go for a light run", "severity": 2, "alone": "alone", "duration": 30, "location": None},
    {"cat": "family anxiety", "activity": "quick yoga", "severity": 2, "alone": "alone", "duration": 20, "location": None},
    {"cat": "family anxiety", "activity": "go for a walk", "severity": 2, "alone": "alone", "duration": 30, "location": None},
    {"cat": "family anxiety", "activity": "Visit interaction check in", "severity": 2, "alone": "alone", "duration": 20, "location": None},
    {"cat": "family anxiety", "activity": "Visualise woodland", "severity": 2, "alone": "alone", "duration": 5, "location": None},
    {
        "cat": "family anxiety",
        "activity": "follow on call with father",
        "severity": 2,
        "alone": "alone or combination",
        "duration": 15,
        "location": "after call with father",
    },
    {
        "cat": "family anxiety",
        "activity": "contact community (sister)",
        "severity": 2,
        "alone": "alone or combination",
        "duration": 15,
        "location": "after call with father",
    },
    {"cat": "motivation", "activity": "yoga lesson", "severity": 0, "alone": "alone", "duration": 30, "location": None},
    {"cat": "motivation", "activity": "stream music concert", "severity": 0, "alone": "alone", "duration": 60, "location": None},
    {"cat": "motivation", "activity": "meditation lesson", "severity": 0, "alone": "alone", "duration": 100, "location": None},
    {"cat": "motivation", "activity": "review long term goals", "severity": 0, "alone": "alone", "duration": 60, "location": None},
    {"cat": "eat", "activity": "affirmation 5 -eating", "severity": 4, "alone": "alone", "duration": 1, "location": "before going out"},
    {"cat": "eat", "activity": "community", "severity": 4, "alone": "alone or combination", "duration": 15, "location": None},
    {"cat": "eat", "activity": "eat protein bar", "severity": 4, "alone": "combination", "duration": 10, "location": None},
    {"cat": "eat", "activity": "fruit drink", "severity": 4, "alone": "combination", "duration": 10, "location": None},
    {"cat": "eat", "activity": "Avoid coffee, alcohol,", "severity": None, "alone": "alone", "duration": None, "location": None},
    {"cat": "eat", "activity": "affirmation 5 -eating", "severity": 3, "alone": "alone", "duration": 1, "location": "before going out"},
    {"cat": "eat", "activity": "eat protein bar", "severity": 3, "alone": "alone or combination", "duration": 10, "location": None},
    {"cat": "eat", "activity": "fruit drink", "severity": 3, "alone": "combination", "duration": 10, "location": None},
    {"cat": "eat", "activity": "Avoid coffee, alcohol,", "severity": 3, "alone": "alone", "duration": None, "location": None},
    {"cat": "eat", "activity": "affirmation 5 -eating", "severity": 2, "alone": "alone", "duration": 1, "location": "before going out"},
    {"cat": "eat", "activity": "eat protein bar", "severity": 2, "alone": "alone or combination", "duration": 10, "location": None},
    {"cat": "eat", "activity": "fruit drink", "severity": 2, "alone": "combination", "duration": 10, "location": None},
    {"cat": "eat", "activity": "Avoid coffee, alcohol,", "severity": 2, "alone": "alone", "duration": None, "location": None},
    {"cat": "sleep", "activity": "sleep routine", "severity": 4, "alone": "alone", "duration": "30,60", "location": "before bed"},
    {"cat": "sleep", "activity": "community", "severity": 4, "alone": "alone or combination", "duration": 15, "location": None},
    {"cat": "sleep", "activity": "affirmation 4 - sleep", "severity": 4, "alone": "alone", "duration": 1, "location": "before bed"},
    {"cat": "sleep", "activity": "meditation app", "severity": 4, "alone": "alone or combination", "duration": 30, "location": "before bed"},
    {"cat": "sleep", "activity": "relaxing yoga", "severity": 4, "alone": "combination", "duration": 30, "location": "before bed"},
    {"cat": "sleep", "activity": "body scan meditation", "severity": 4, "alone": "combination", "duration": 30, "location": "before bed"},
    {"cat": "sleep", "activity": "progressive muscle relaxation", "severity": 4, "alone": "alone", "duration": 5, "location": "before bed"},
    {"cat": "sleep", "activity": "affirmation 4 - sleep", "severity": 3, "alone": "alone", "duration": 1, "location": "before bed"},
    {"cat": "sleep", "activity": "meditation app", "severity": 3, "alone": "alone or combination", "duration": 30, "location": "before bed"},
    {"cat": "sleep", "activity": "relaxing yoga", "severity": 3, "alone": "combination", "duration": 30, "location": "before bed"},
    {"cat": "sleep", "activity": "warm bath / aroma oils", "severity": 3, "alone": "alone", "duration": 30, "location": "before bed"},
    {"cat": "sleep", "activity": "breathing box", "severity": 3, "alone": "alone", "duration": 5, "location": "before bed"},
]

# Load the data from JSON
mh_sug = pd.DataFrame(mh_sug_json)


def get_suggestion(category, severity, database):
    # Filter the suggestions based on category and severity
    ind = mh_sug[(mh_sug["cat"] == category) & (mh_sug["severity"] == severity)].index
    cand = mh_sug.loc[ind, "activity"].tolist()

    if len(cand) == 0:
        raise ValueError("no suggestion found")

    if len(cand) > 1:
        score = []
        recent_time_limit = database["time"].max() - pd.Timedelta(days=2)
        for c in cand:
            lp = 0.0
            # Filter database for the last 2 days
            recent_entries = database[database["time"] > recent_time_limit]
            for _, r in recent_entries.iterrows():
                # If same suggestion was done earlier
                if r["activity"] == c:
                    lp -= 10
            score.append(lp)
        return cand[np.argmax(score)]

    return cand[0]
