"""Added affirmation_number field

Revision ID: 064acec91161
Revises: 2559c993fbc7
Create Date: 2024-10-09 13:08:16.726897

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '064acec91161'
down_revision: Union[str, None] = '2559c993fbc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CardDetail', sa.Column('affirmation_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('CardDetail', 'affirmation_number')
    # ### end Alembic commands ###
