"""Added voice therapy sessions table

Revision ID: voice_therapy_001
Revises:
Create Date: 2024-12-22 10:00:00.000000

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'voice_therapy_001'
down_revision = '064acec91161'  # Added affirmation_number field
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_therapy_sessions',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('therapy_type', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('session_summary', sa.Text(), nullable=True),
    sa.Column('mood_before', sa.String(), nullable=True),
    sa.Column('mood_after', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_voice_therapy_sessions_session_id'), 'voice_therapy_sessions', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voice_therapy_sessions_session_id'), table_name='voice_therapy_sessions')
    op.drop_table('voice_therapy_sessions')
    # ### end Alembic commands ###
