"""Created CategoryEnum1

Revision ID: 2559c993fbc7
Revises: 2644707733a7
Create Date: 2024-10-01 15:00:36.120973

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2559c993fbc7'
down_revision: Union[str, None] = '2644707733a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CardDetail', sa.Column('category', sa.Enum('NUTRITION', 'INNER_GOALS', 'RELATIONSHIPS', 'HOBBIES', 'SLEEP', 'EXERCISE', 'SELF_DEVELOPMENT', 'MOOD', name='categoryenum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('CardDetail', 'category')
    # ### end Alembic commands ###
