"""Created cognitiveFingerprint

Revision ID: 28eef818ed5f
Revises: ce6192464459
Create Date: 2025-02-05 18:16:32.362584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28eef818ed5f'
down_revision: Union[str, None] = 'ce6192464459'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CognitiveFingerprint',
    sa.Column('fingerprint_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('work_anxiety', sa.Float(), nullable=False),
    sa.Column('social_anxiety', sa.Float(), nullable=False),
    sa.Column('family_anxiety', sa.Float(), nullable=False),
    sa.Column('eating_anxiety', sa.Float(), nullable=False),
    sa.Column('sleeping_anxiety', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('fingerprint_id')
    )
    op.create_index(op.f('ix_CognitiveFingerprint_fingerprint_id'), 'CognitiveFingerprint', ['fingerprint_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_CognitiveFingerprint_fingerprint_id'), table_name='CognitiveFingerprint')
    op.drop_table('CognitiveFingerprint')
    # ### end Alembic commands ###
