"""added completed field to UserGoals"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '2c4d57f826a4'
down_revision: Union[str, None] = '9fbcaac4a990'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserGoals', sa.Column('completed', sa.Integer(), nullable=True, server_default='0'))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UserGoals', 'completed')
    # ### end Alembic commands ###