"""Added Goal related tables

Revision ID: 39cf9c9aacbd
Revises: fa4a1980e6fa
Create Date: 2024-11-28 15:21:50.741516

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '39cf9c9aacbd'
down_revision: Union[str, None] = 'fa4a1980e6fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
