"""added completed morning orientation field to user

Revision ID: 733318df68d0
Revises: 2c4d57f826a4
Create Date: 2024-12-05 14:56:41.795486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '733318df68d0'
down_revision: Union[str, None] = '2c4d57f826a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('completed_morning_orientation', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'completed_morning_orientation')
    # ### end Alembic commands ###
