"""Added value column to CognitiveScoreImpact

Revision ID: 7d5dc5fdd197
Revises: b94aa73b86ca
Create Date: 2024-08-24 16:00:07.624290

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7d5dc5fdd197'
down_revision: Union[str, None] = 'b94aa73b86ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CognitiveScoreImpact', sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('CognitiveScoreImpact', 'value')
    # ### end Alembic commands ###
