"""Initial migration

Revision ID: 8417e13d114c
Revises: ac646ceb952d
Create Date: 2024-08-23 13:54:19.532347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8417e13d114c'
down_revision: Union[str, None] = 'ac646ceb952d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CardDetail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_type', sa.Enum('suggestion', 'calendar', 'option', name='cardtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('duration', sa.Interval(), nullable=False),
    sa.Column('tod', sa.Enum('MORNING', 'AFTERNOON', 'EVENING', 'NIGHT', 'ANY', name='timeofday'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_CardDetail_id'), 'CardDetail', ['id'], unique=False)
    op.create_table('GoogleEventCreators',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('displayName', sa.String(), nullable=True),
    sa.Column('self_field', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_GoogleEventCreators_id'), 'GoogleEventCreators', ['id'], unique=False)
    op.create_table('GoogleEventDates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('dateTime', sa.DateTime(), nullable=True),
    sa.Column('timeZone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_GoogleEventDates_id'), 'GoogleEventDates', ['id'], unique=False)
    op.create_table('GoogleEventOrganizers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('displayName', sa.String(), nullable=True),
    sa.Column('self_field', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_GoogleEventOrganizers_id'), 'GoogleEventOrganizers', ['id'], unique=False)
    op.create_table('Objective',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Objective_id'), 'Objective', ['id'], unique=False)
    op.create_table('User',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('firstname', sa.String(length=255), nullable=False),
    sa.Column('surname', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('home', sa.String(length=255), nullable=True),
    sa.Column('office', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_User_user_id'), 'User', ['user_id'], unique=False)
    op.create_table('CognitiveScore',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_CognitiveScore_id'), 'CognitiveScore', ['id'], unique=False)
    op.create_table('ExternalTokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('token_type', sa.String(length=50), nullable=False),
    sa.Column('token_value', sa.String(length=1024), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ExternalTokens_id'), 'ExternalTokens', ['id'], unique=False)
    op.create_table('FitbitHeartLog',
    sa.Column('log_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.Date(), nullable=False),
    sa.Column('resting_heart_rate', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_FitbitHeartLog_log_id'), 'FitbitHeartLog', ['log_id'], unique=False)
    op.create_table('FitbitSleepLog',
    sa.Column('log_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_of_sleep', sa.Date(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('efficiency', sa.Integer(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('info_code', sa.Integer(), nullable=True),
    sa.Column('is_main_sleep', sa.Boolean(), nullable=True),
    sa.Column('minutes_after_wakeup', sa.Integer(), nullable=True),
    sa.Column('minutes_asleep', sa.Integer(), nullable=True),
    sa.Column('minutes_awake', sa.Integer(), nullable=True),
    sa.Column('minutes_to_fall_asleep', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('time_in_bed', sa.Integer(), nullable=True),
    sa.Column('log_type', sa.String(length=50), nullable=True),
    sa.Column('sleep_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_FitbitSleepLog_log_id'), 'FitbitSleepLog', ['log_id'], unique=False)
    op.create_table('GoogleCalendarEvents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('etag', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('htmlLink', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('colorId', sa.String(), nullable=True),
    sa.Column('endTimeUnspecified', sa.Boolean(), nullable=True),
    sa.Column('recurrence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recurringEventId', sa.String(), nullable=True),
    sa.Column('transparency', sa.String(), nullable=True),
    sa.Column('visibility', sa.String(), nullable=True),
    sa.Column('iCalUID', sa.String(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('hangoutLink', sa.String(), nullable=True),
    sa.Column('anyoneCanAddSelf', sa.Boolean(), nullable=True),
    sa.Column('guestsCanInviteOthers', sa.Boolean(), nullable=True),
    sa.Column('guestsCanModify', sa.Boolean(), nullable=True),
    sa.Column('guestsCanSeeOtherGuests', sa.Boolean(), nullable=True),
    sa.Column('privateCopy', sa.Boolean(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('source_title', sa.String(), nullable=True),
    sa.Column('eventType', sa.String(), nullable=True),
    sa.Column('creator_id', sa.String(), nullable=True),
    sa.Column('organizer_id', sa.String(), nullable=True),
    sa.Column('start_id', sa.String(), nullable=True),
    sa.Column('end_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['GoogleEventCreators.id'], ),
    sa.ForeignKeyConstraint(['end_id'], ['GoogleEventDates.id'], ),
    sa.ForeignKeyConstraint(['organizer_id'], ['GoogleEventOrganizers.id'], ),
    sa.ForeignKeyConstraint(['start_id'], ['GoogleEventDates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_GoogleCalendarEvents_id'), 'GoogleCalendarEvents', ['id'], unique=False)
    op.create_table('UserPreferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('preferenceName', sa.String(), nullable=False),
    sa.Column('preferenceMetric', sa.Numeric(), nullable=True),
    sa.Column('category', sa.Enum('FOOD', 'EDUCATION', 'PERSONAL_CARE', 'ENTERTAINMENT', 'EXERCISE', name='categoryenum'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('FitbitCustomHeartRateZone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('min', sa.Integer(), nullable=False),
    sa.Column('max', sa.Integer(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('calories_out', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['log_id'], ['FitbitHeartLog.log_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_FitbitCustomHeartRateZone_id'), 'FitbitCustomHeartRateZone', ['id'], unique=False)
    op.create_table('FitbitHeartRateZone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('min', sa.Integer(), nullable=False),
    sa.Column('max', sa.Integer(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('calories_out', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['log_id'], ['FitbitHeartLog.log_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_FitbitHeartRateZone_id'), 'FitbitHeartRateZone', ['id'], unique=False)
    op.create_table('FitbitSleepLevel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_id', sa.BigInteger(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('seconds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['log_id'], ['FitbitSleepLog.log_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_FitbitSleepLevel_id'), 'FitbitSleepLevel', ['id'], unique=False)
    op.create_table('FitbitSleepSummary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_id', sa.BigInteger(), nullable=False),
    sa.Column('level_type', sa.String(length=50), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('thirty_day_avg_minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['log_id'], ['FitbitSleepLog.log_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_FitbitSleepSummary_id'), 'FitbitSleepSummary', ['id'], unique=False)
    op.create_table('GoogleConferenceData',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('createRequest', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('entryPoints', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('conferenceSolution', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('conferenceId', sa.String(), nullable=True),
    sa.Column('signature', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['GoogleCalendarEvents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_GoogleConferenceData_id'), 'GoogleConferenceData', ['id'], unique=False)
    op.create_table('GoogleEventAttendees',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('displayName', sa.String(), nullable=True),
    sa.Column('organizer', sa.Boolean(), nullable=True),
    sa.Column('self_field', sa.Boolean(), nullable=True),
    sa.Column('resource', sa.Boolean(), nullable=True),
    sa.Column('optional', sa.Boolean(), nullable=True),
    sa.Column('responseStatus', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('additionalGuests', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['GoogleCalendarEvents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_GoogleEventAttendees_id'), 'GoogleEventAttendees', ['id'], unique=False)
    op.create_table('GoogleEventReminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['GoogleCalendarEvents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_GoogleEventReminders_id'), 'GoogleEventReminders', ['id'], unique=False)
    op.create_table('UserCard',
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('card_details_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('recurrence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('calendar_event_id', sa.String(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['calendar_event_id'], ['GoogleCalendarEvents.id'], ),
    sa.ForeignKeyConstraint(['card_details_id'], ['CardDetail.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('card_id')
    )
    op.create_index(op.f('ix_UserCard_card_id'), 'UserCard', ['card_id'], unique=False)
    op.create_table('CardCompletionDetail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ongoing', 'missed', 'completed', 'deleted', name='cardstatus'), nullable=False),
    sa.Column('completion_level', sa.Enum('partly', 'fully', 'incomplete', name='completionlevel'), nullable=False),
    sa.Column('how_was_it', sa.Enum('terrible', 'bad', 'ok', 'good', 'awesome', name='howwasit'), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['UserCard.card_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_CardCompletionDetail_id'), 'CardCompletionDetail', ['id'], unique=False)
    op.create_table('CognitiveScoreImpact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cognitive_score_id', sa.Integer(), nullable=False),
    sa.Column('card_completion_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['card_completion_id'], ['CardCompletionDetail.id'], ),
    sa.ForeignKeyConstraint(['cognitive_score_id'], ['CognitiveScore.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_CognitiveScoreImpact_id'), 'CognitiveScoreImpact', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_CognitiveScoreImpact_id'), table_name='CognitiveScoreImpact')
    op.drop_table('CognitiveScoreImpact')
    op.drop_index(op.f('ix_CardCompletionDetail_id'), table_name='CardCompletionDetail')
    op.drop_table('CardCompletionDetail')
    op.drop_index(op.f('ix_UserCard_card_id'), table_name='UserCard')
    op.drop_table('UserCard')
    op.drop_index(op.f('ix_GoogleEventReminders_id'), table_name='GoogleEventReminders')
    op.drop_table('GoogleEventReminders')
    op.drop_index(op.f('ix_GoogleEventAttendees_id'), table_name='GoogleEventAttendees')
    op.drop_table('GoogleEventAttendees')
    op.drop_index(op.f('ix_GoogleConferenceData_id'), table_name='GoogleConferenceData')
    op.drop_table('GoogleConferenceData')
    op.drop_index(op.f('ix_FitbitSleepSummary_id'), table_name='FitbitSleepSummary')
    op.drop_table('FitbitSleepSummary')
    op.drop_index(op.f('ix_FitbitSleepLevel_id'), table_name='FitbitSleepLevel')
    op.drop_table('FitbitSleepLevel')
    op.drop_index(op.f('ix_FitbitHeartRateZone_id'), table_name='FitbitHeartRateZone')
    op.drop_table('FitbitHeartRateZone')
    op.drop_index(op.f('ix_FitbitCustomHeartRateZone_id'), table_name='FitbitCustomHeartRateZone')
    op.drop_table('FitbitCustomHeartRateZone')
    op.drop_table('UserPreferences')
    op.drop_index(op.f('ix_GoogleCalendarEvents_id'), table_name='GoogleCalendarEvents')
    op.drop_table('GoogleCalendarEvents')
    op.drop_index(op.f('ix_FitbitSleepLog_log_id'), table_name='FitbitSleepLog')
    op.drop_table('FitbitSleepLog')
    op.drop_index(op.f('ix_FitbitHeartLog_log_id'), table_name='FitbitHeartLog')
    op.drop_table('FitbitHeartLog')
    op.drop_index(op.f('ix_ExternalTokens_id'), table_name='ExternalTokens')
    op.drop_table('ExternalTokens')
    op.drop_index(op.f('ix_CognitiveScore_id'), table_name='CognitiveScore')
    op.drop_table('CognitiveScore')
    op.drop_index(op.f('ix_User_user_id'), table_name='User')
    op.drop_table('User')
    op.drop_index(op.f('ix_Objective_id'), table_name='Objective')
    op.drop_table('Objective')
    op.drop_index(op.f('ix_GoogleEventOrganizers_id'), table_name='GoogleEventOrganizers')
    op.drop_table('GoogleEventOrganizers')
    op.drop_index(op.f('ix_GoogleEventDates_id'), table_name='GoogleEventDates')
    op.drop_table('GoogleEventDates')
    op.drop_index(op.f('ix_GoogleEventCreators_id'), table_name='GoogleEventCreators')
    op.drop_table('GoogleEventCreators')
    op.drop_index(op.f('ix_CardDetail_id'), table_name='CardDetail')
    op.drop_table('CardDetail')
    # ### end Alembic commands ###
