"""Initial migration

Revision ID: ac646ceb952d
Revises: f7ecf2c98c6c
Create Date: 2024-08-23 13:41:58.125642

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'ac646ceb952d'
down_revision: Union[str, None] = 'f7ecf2c98c6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
