"""Added MH Categories

Revision ID: ad581119018b
Revises: 064acec91161
Create Date: 2024-11-03 21:12:08.941569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad581119018b'
down_revision: Union[str, None] = '064acec91161'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mh_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_name')
    )
    op.create_index(op.f('ix_mh_categories_id'), 'mh_categories', ['id'], unique=False)
    op.create_table('card_mh_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_detail_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_detail_id'], ['CardDetail.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['mh_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_mh_categories_id'), 'card_mh_categories', ['id'], unique=False)
    op.add_column('CardDetail', sa.Column('severity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('CardDetail', 'severity')
    op.drop_index(op.f('ix_card_mh_categories_id'), table_name='card_mh_categories')
    op.drop_table('card_mh_categories')
    op.drop_index(op.f('ix_mh_categories_id'), table_name='mh_categories')
    op.drop_table('mh_categories')
    # ### end Alembic commands ###
