"""Added value column to CognitiveScoreImpact

Revision ID: b94aa73b86ca
Revises: 8417e13d114c
Create Date: 2024-08-24 15:58:44.485962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b94aa73b86ca'
down_revision: Union[str, None] = '8417e13d114c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
