"""Moved revision field to CardMHCategory

Revision ID: c5a22ae17e90
Revises: a49404c570e0
Create Date: 2024-11-18 15:59:57.817520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5a22ae17e90'
down_revision: Union[str, None] = 'a49404c570e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('CardDetail', 'severity')
    op.add_column('card_mh_categories', sa.Column('severity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card_mh_categories', 'severity')
    op.add_column('CardDetail', sa.Column('severity', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
