"""Added new_cognitive_score column to CognitiveScoreImpact

Revision ID: c89c214567cd
Revises: 7d5dc5fdd197
Create Date: 2024-08-24 17:34:39.604971

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c89c214567cd'
down_revision: Union[str, None] = '7d5dc5fdd197'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CognitiveScoreImpact', sa.Column('new_cogntive_score', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('CognitiveScoreImpact', 'new_cogntive_score')
    # ### end Alembic commands ###
