"""Added morning orientation completed date field to user

Revision ID: ce6192464459
Revises: 733318df68d0
Create Date: 2025-01-15 13:45:01.316158

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ce6192464459'
down_revision: Union[str, None] = '733318df68d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('completed_morning_orientation_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'completed_morning_orientation_date')
    # ### end Alembic commands ###
