"""Added special action to CardDetail

Revision ID: d7aedaa97b56
Revises: deee5da3b87e
Create Date: 2024-10-01 14:09:11.298885

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy import Enum

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd7aedaa97b56'
down_revision: Union[str, None] = 'deee5da3b87e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    specialactions = Enum('NONE', 'BREATHING', 'AFFIRMATION', name='specialactions')
    specialactions.create(op.get_bind(), checkfirst=True)
    op.add_column('CardDetail', sa.Column('special_card_action', sa.Enum('NONE', 'BREATHING', 'AFFIRMATION', name='specialactions'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('CardDetail', 'special_card_action')
    # ### end Alembic commands ###
