"""fixed spelling error of new_cognitive_score column

Revision ID: e726b5492d87
Revises: c89c214567cd
Create Date: 2024-08-24 17:54:59.101337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'e726b5492d87'
down_revision: Union[str, None] = 'c89c214567cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CognitiveScoreImpact', sa.Column('new_cognitive_score', sa.Numeric(precision=10, scale=2), nullable=True))
    op.drop_column('CognitiveScoreImpact', 'new_cogntive_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CognitiveScoreImpact', sa.Column('new_cogntive_score', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.drop_column('CognitiveScoreImpact', 'new_cognitive_score')
    # ### end Alembic commands ###
