"""Init database

Revision ID: f7ecf2c98c6c
Revises:
Create Date: 2024-08-23 13:39:30.386802

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'f7ecf2c98c6c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
