"""Added Goal related tables

Revision ID: fa4a1980e6fa
Revises: c5a22ae17e90
Create Date: 2024-11-27 16:58:25.775438

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'fa4a1980e6fa'
down_revision: Union[str, None] = 'c5a22ae17e90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
